services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    # command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
    environment:
      SECRET_KEY: your-secret-key
      DATABASE_URL: mysql+pymysql://flaskuser:flaskpass@db:3306/flaskdb
      FLASK_APP: app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: